target 'SYYoukuUrlFetcher', :exclusive => true do
  pod "SYYoukuUrlFetcher", :path => "../"
  pod 'AFNetworking', '~> 2.3'
end

target 'Tests', :exclusive => true do
  pod "SYYoukuUrlFetcher", :path => "../"

  pod 'Kiwi'
end
